---
title: "NYC Restaurant Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(plotly)
library(flexdashboard)
library(p8105.datasets)

nycrest_data = rest_inspec %>% 
  janitor::clean_names() %>% 
  drop_na(action, score, grade) %>% 
  subset(boro != "Missing")

common_cuisines =
  nycrest_data %>% 
  count(cuisine_description, sort = TRUE) %>% 
  top_n(8) %>% 
  select(cuisine_description)
```

Cuisine Types {data-width=650}
-----------------------------------------------------------------------

### 10 Most Common Cuisines
```{r}
inner_join(nycrest_data, common_cuisines,
             by = "cuisine_description") %>% 
  count(cuisine_description) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>% 
  plot_ly(x = ~cuisine_description, y = ~n, color = ~cuisine_description, type = "bar") %>% 
    layout(legend = list(orientation = "h", xanchor = "center", x = 0.5),
          xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE)
    )
```

Restaurant Inspections {data-width=350}
-----------------------------------------------------------------------

### Scores, by boro
```{r}
nycrest_data %>% 
  mutate(boro = fct_reorder(boro, score)) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box", alpha = 0.5) %>% 
    layout(legend = list(orientation = "h", xanchor = "center", x = 0.5))
```

###  Restaurant grades
```{r}
nycrest_data %>% 
  count(grade) %>% 
  mutate(grade = fct_reorder(grade, n)) %>% 
  plot_ly(x = ~grade, y = ~n, color = ~grade, type = "bar") %>% 
    layout(legend = list(orientation = "h", xanchor = "center", x = 0.5))
```